- name: restart_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: reload_prometheus
  uri:
    url: http://20.218.95.248:9090/-/reload
    method: POST
    status_code: 200
